"""add xray api fields to nodes

Revision ID: 0a3cd65f714b
Revises: 0f8559252abf
Create Date: 2026-08-17 12:58:32.416685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3cd65f714b'
down_revision: Union[str, None] = '0f8559252abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('xray_api_host', sa.String(length=255), nullable=False))
    op.add_column('nodes', sa.Column('xray_api_port', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'xray_api_port')
    op.drop_column('nodes', 'xray_api_host')
    # ### end Alembic commands ###
