"""add hysteria obfs password to nodes

Revision ID: 32ab632718d5
Revises: d37b2ad42e70
Create Date: 2026-08-23 20:37:28.190193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ab632718d5'
down_revision: Union[str, None] = 'd37b2ad42e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('hysteria_obfs_password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'hysteria_obfs_password')
    # ### end Alembic commands ###
