"""add hysteria2 fields to nodes and subscriptions

Revision ID: d37b2ad42e70
Revises: f7a33067d70f
Create Date: 2026-08-23 20:22:14.585014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37b2ad42e70'
down_revision: Union[str, None] = 'f7a33067d70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('hysteria_port', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('hysteria_cert_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('subscriptions', sa.Column('hysteria_password', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'hysteria_password')
    op.drop_column('nodes', 'hysteria_cert_fingerprint')
    op.drop_column('nodes', 'hysteria_port')
    # ### end Alembic commands ###
