"""add multi-node fields to nodes table

Revision ID: dc2647d8c6c2
Revises: 0a3cd65f714b
Create Date: 2026-08-17 13:32:20.364644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2647d8c6c2'
down_revision: Union[str, None] = '0a3cd65f714b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('is_local', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('nodes', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    op.add_column('nodes', sa.Column('status', sa.String(length=32), nullable=False, server_default='unknown'))
    op.add_column('nodes', sa.Column('max_users', sa.Integer(), nullable=True))
    op.alter_column('nodes', 'is_local', server_default=None)
    op.alter_column('nodes', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'max_users')
    op.drop_column('nodes', 'status')
    op.drop_column('nodes', 'api_key_hash')
    op.drop_column('nodes', 'is_local')
    # ### end Alembic commands ###
