"""add agent host and port fields to nodes

Revision ID: f7a33067d70f
Revises: dc2647d8c6c2
Create Date: 2026-08-17 13:56:12.047057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a33067d70f'
down_revision: Union[str, None] = 'dc2647d8c6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('agent_host', sa.String(length=255), nullable=True))
    op.add_column('nodes', sa.Column('agent_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'agent_port')
    op.drop_column('nodes', 'agent_host')
    # ### end Alembic commands ###
